### ISSUE TITLE
Llama 3

### ISSUE THREAD

**Issue by peregilk** [stanford-crfm/levanter#565]
Do you have any plans for adding for supporting Llama-3? Any idea how complex this would be, apart from new configs?

**Comment by dlwh** [comment]
@Helw150 said it worked out of the box. Just configs I think

**Comment by peregilk** [comment]
Thats fantastic, @dlwh! Great if you could share your configs @Helw150.

I must admit I have not dug into the details here yet, but I understood the biggest architectural changes were using a larger tokenizer, and adding GQA to the smaller models. I havent seen GQA used in any of the Levanter models, but found a post saying it was supported. Can this also just be enabled through the configs?

I also read a post about them doing some masking on longer sequences so that the attention did not "spill over" to new documents.

**Comment by peregilk** [comment]
The model seems to start training with:

```
data:  
  tokenizer: "meta-llama/Meta-Llama-3-8B"
model:
  type: llama
initialize_from_hf: "meta-llama/Meta-Llama-3-8B"
use_hf_model_config: true
```
However, I keep getting the message: `"The tokenizers appear to be different. You may want to check this."`. 

Not really sure what is causing this.

**Comment by peregilk** [comment]
@dlwh. Unfortuantely, I can not seem to get it to work right out of the box. The model is training, but when trying to train on a domain specific corpus, the loss is starting way too high, and never fully recovers.

I am pretty sure the issue is the vocab size here. I can not seem to override the vocab size in the model config. 

This line seem to return the default Llama tokenizer:
https://github.com/stanford-crfm/levanter/blob/bd2aad66a2c301a52b52a65b455617aa2e452ba6/src/levanter/main/train_lm.py#L62

While it is overwritten later, I think this is the main issue. 

I have tried both reading the configs from HF, and creating them from scratch. 

Please advice.

**Comment by dlwh** [comment]
ok i'll try to take a look this weekend. Do you have a full config you can use a reproducer by any chance?

**Comment by peregilk** [comment]
Awesome. Here are the two config I have been using. Just removing the bucket urls.

```
data:
  train_urls:
    - "gs://mydatabucket/train-shard-{0001..0147}-of-0147.json.gz"
  validation_urls:
    - "gs://mydatabucket/NCC_plus_scandi/validation-shard-0001-of-0001.json.gz"
  cache_dir: "gs://mycachebucket/NCC_plus_scandi/tokenized/llama3hfconfigfalse/"
  tokenizer: "meta-llama/Meta-Llama-3-8B"
model:
  type: llama
  seq_len: 2048
  hidden_dim: 4096
  intermediate_dim: 14336
  num_layers: 32
  num_heads: 32
  num_kv_heads: 8
  initializer_range: 0.02
  use_flash_attention: true
initialize_from_hf: "meta-llama/Meta-Llama-3-8B"
use_hf_model_config: false
trainer:
  wandb:
    entity: "myentity"
    project: "myproject"
    tags: ["llama3"]
    name: north-llamatre-hfconfigfalse
  mp: p=f32,c=bfloat16
  train_batch_size: 256 
  num_train_steps: 10000
  steps_per_eval: 250
  tensor_parallel_axes: ["mlp", "heads"]
  fsdp_axis: "embed"
  batch_axis: "batch"
  checkpointer:
    base_path: "gs://mycheckpointbucket/north-llama3-hfconfigfalse/checkpoints"
    keep:
      - every: 1000
optimizer:
  learning_rate: 1.2e-5
  weight_decay: 0.1
  min_lr_ratio: 0.1
  warmup: 1000
hf_save_steps: 5000
hf_save_path: "gs://myhfbucket/north-llama3-hfconfigfalse/hf"
```

I have also tried setting
`use_hf_model_config: true`

This gave the same result.

What I am seeing can be illustrated here:
![image](https://github.com/stanford-crfm/levanter/assets/9079808/819df9e6-7f76-41e9-977e-d29351c9f821)

The red line is the loss of a Mistral model. The grey line is from Llama3. Apart from that, the settings are identical, and they are both trying to use the HF tokenizer. The pattern is very similar to what we are seeing with just hot-swappng to a new tokenizer.
